// This parent script provides the Android Gradle Plugin to its sub-modules.
buildscript {
  repositories {
    mavenCentral()
    google()
    gradlePluginPortal()
  }
  dependencies {
    classpath "com.android.tools.build:gradle:8.4.1"
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.23"
  }
}

// This provides common repositories to all client sub-modules.
allprojects {
  repositories {
    mavenCentral()
    google()
    maven { url 'https://s01.oss.sonatype.org' }
    mavenLocal()
  }
}
